"""
job_profiles.py
Database of 40+ job roles with required skills, weights, salary ranges.
Each profile defines what skills matter most for that role.
"""

JOB_PROFILES = [

    # ── FRONTEND ────────────────────────────────────────────────────────────
    {
        "title":       "Frontend Developer",
        "category":    "Frontend",
        "emoji":       "🎨",
        "core_skills": ["React", "JavaScript", "HTML/CSS"],
        "good_skills": ["TypeScript", "Tailwind", "Redux", "Webpack/Vite", "Git"],
        "bonus_skills":["Next.js", "Vue", "Testing", "Figma/UI"],
        "salary_pkr":  "80K – 150K/month",
        "salary_usd":  "$25K – $55K/year",
        "demand":      "Very High",
        "description": "Build user interfaces and web experiences using modern JavaScript frameworks.",
    },
    {
        "title":       "React Developer",
        "category":    "Frontend",
        "emoji":       "⚛️",
        "core_skills": ["React", "JavaScript", "TypeScript"],
        "good_skills": ["Redux", "Next.js", "REST APIs", "Git", "HTML/CSS"],
        "bonus_skills":["Testing", "Webpack/Vite", "GraphQL"],
        "salary_pkr":  "90K – 180K/month",
        "salary_usd":  "$30K – $70K/year",
        "demand":      "Very High",
        "description": "Specialise in building scalable React applications with modern state management.",
    },
    {
        "title":       "Next.js Developer",
        "category":    "Frontend",
        "emoji":       "▲",
        "core_skills": ["Next.js", "React", "TypeScript"],
        "good_skills": ["JavaScript", "Tailwind", "REST APIs", "Git"],
        "bonus_skills":["GraphQL", "Redux", "Testing"],
        "salary_pkr":  "100K – 200K/month",
        "salary_usd":  "$35K – $80K/year",
        "demand":      "High",
        "description": "Build server-side rendered and static web applications using Next.js.",
    },
    {
        "title":       "Vue.js Developer",
        "category":    "Frontend",
        "emoji":       "💚",
        "core_skills": ["Vue", "JavaScript", "HTML/CSS"],
        "good_skills": ["TypeScript", "Tailwind", "REST APIs", "Git"],
        "bonus_skills":["Webpack/Vite", "Testing", "Redux"],
        "salary_pkr":  "80K – 160K/month",
        "salary_usd":  "$28K – $65K/year",
        "demand":      "Medium",
        "description": "Develop progressive web apps using the Vue.js ecosystem.",
    },
    {
        "title":       "UI/UX Developer",
        "category":    "Frontend",
        "emoji":       "✏️",
        "core_skills": ["Figma/UI", "HTML/CSS", "JavaScript"],
        "good_skills": ["React", "Tailwind", "Agile/Scrum", "Git"],
        "bonus_skills":["Vue", "Angular", "TypeScript"],
        "salary_pkr":  "70K – 140K/month",
        "salary_usd":  "$22K – $50K/year",
        "demand":      "High",
        "description": "Bridge design and development — create beautiful, usable interfaces.",
    },

    # ── BACKEND ─────────────────────────────────────────────────────────────
    {
        "title":       "Backend Developer",
        "category":    "Backend",
        "emoji":       "⚙️",
        "core_skills": ["Python", "REST APIs", "SQL"],
        "good_skills": ["FastAPI", "Docker", "Git", "MongoDB", "Linux"],
        "bonus_skills":["AWS", "Redis", "Microservices", "Testing"],
        "salary_pkr":  "90K – 180K/month",
        "salary_usd":  "$30K – $70K/year",
        "demand":      "Very High",
        "description": "Build robust server-side logic, APIs, and database integrations.",
    },
    {
        "title":       "Python Developer",
        "category":    "Backend",
        "emoji":       "🐍",
        "core_skills": ["Python", "REST APIs", "SQL"],
        "good_skills": ["FastAPI", "Django", "Flask", "Git", "Docker"],
        "bonus_skills":["AWS", "MongoDB", "Testing", "Linux"],
        "salary_pkr":  "85K – 170K/month",
        "salary_usd":  "$28K – $65K/year",
        "demand":      "Very High",
        "description": "Develop backend systems, automation scripts, and APIs using Python.",
    },
    {
        "title":       "Node.js Developer",
        "category":    "Backend",
        "emoji":       "🟢",
        "core_skills": ["Node.js", "JavaScript", "REST APIs"],
        "good_skills": ["Express", "MongoDB", "SQL", "Git", "Docker"],
        "bonus_skills":["TypeScript", "GraphQL", "AWS", "Testing"],
        "salary_pkr":  "85K – 175K/month",
        "salary_usd":  "$28K – $68K/year",
        "demand":      "Very High",
        "description": "Build fast, scalable backend services using Node.js and Express.",
    },
    {
        "title":       "Django Developer",
        "category":    "Backend",
        "emoji":       "🎸",
        "core_skills": ["Python", "Django", "SQL"],
        "good_skills": ["REST APIs", "Git", "Docker", "Linux"],
        "bonus_skills":["AWS", "Redis", "Testing", "GraphQL"],
        "salary_pkr":  "80K – 160K/month",
        "salary_usd":  "$25K – $60K/year",
        "demand":      "Medium",
        "description": "Build full-featured web applications using the Django framework.",
    },
    {
        "title":       "FastAPI Developer",
        "category":    "Backend",
        "emoji":       "⚡",
        "core_skills": ["Python", "FastAPI", "REST APIs"],
        "good_skills": ["SQL", "Docker", "Git", "MongoDB"],
        "bonus_skills":["AWS", "Testing", "GraphQL", "Redis"],
        "salary_pkr":  "90K – 180K/month",
        "salary_usd":  "$30K – $72K/year",
        "demand":      "High",
        "description": "Build high-performance APIs using FastAPI and async Python.",
    },
    {
        "title":       "Java Developer",
        "category":    "Backend",
        "emoji":       "☕",
        "core_skills": ["Java", "Spring Boot", "SQL"],
        "good_skills": ["REST APIs", "Git", "Docker", "Agile/Scrum"],
        "bonus_skills":["AWS", "Microservices", "Testing", "Linux"],
        "salary_pkr":  "100K – 200K/month",
        "salary_usd":  "$35K – $80K/year",
        "demand":      "High",
        "description": "Build enterprise-grade applications using Java and Spring Boot.",
    },

    # ── FULL STACK ──────────────────────────────────────────────────────────
    {
        "title":       "Full Stack Developer",
        "category":    "Full Stack",
        "emoji":       "🔥",
        "core_skills": ["React", "Node.js", "SQL"],
        "good_skills": ["JavaScript", "REST APIs", "MongoDB", "Git", "Docker"],
        "bonus_skills":["TypeScript", "AWS", "GraphQL", "Testing"],
        "salary_pkr":  "100K – 220K/month",
        "salary_usd":  "$35K – $85K/year",
        "demand":      "Very High",
        "description": "Own both frontend and backend — build complete web products end to end.",
    },
    {
        "title":       "MERN Stack Developer",
        "category":    "Full Stack",
        "emoji":       "🌐",
        "core_skills": ["MongoDB", "Express", "React", "Node.js"],
        "good_skills": ["JavaScript", "REST APIs", "Git", "HTML/CSS"],
        "bonus_skills":["TypeScript", "Docker", "Redux", "Testing"],
        "salary_pkr":  "95K – 200K/month",
        "salary_usd":  "$32K – $78K/year",
        "demand":      "Very High",
        "description": "Build full-stack JavaScript applications using the MERN stack.",
    },
    {
        "title":       "Full Stack Python Developer",
        "category":    "Full Stack",
        "emoji":       "🐍🎨",
        "core_skills": ["Python", "React", "SQL"],
        "good_skills": ["FastAPI", "Django", "JavaScript", "Git", "Docker"],
        "bonus_skills":["AWS", "MongoDB", "Testing", "TypeScript"],
        "salary_pkr":  "100K – 210K/month",
        "salary_usd":  "$35K – $82K/year",
        "demand":      "High",
        "description": "Build complete products using Python backends with React frontends.",
    },

    # ── MOBILE ──────────────────────────────────────────────────────────────
    {
        "title":       "React Native Developer",
        "category":    "Mobile",
        "emoji":       "📱",
        "core_skills": ["React Native", "JavaScript", "React"],
        "good_skills": ["TypeScript", "REST APIs", "Git", "Firebase"],
        "bonus_skills":["Redux", "Testing", "Android", "iOS/Swift"],
        "salary_pkr":  "90K – 190K/month",
        "salary_usd":  "$30K – $75K/year",
        "demand":      "Very High",
        "description": "Build cross-platform mobile apps for iOS and Android using React Native.",
    },
    {
        "title":       "Flutter Developer",
        "category":    "Mobile",
        "emoji":       "🦋",
        "core_skills": ["Flutter", "REST APIs", "Git"],
        "good_skills": ["Firebase", "SQL", "Android", "Agile/Scrum"],
        "bonus_skills":["iOS/Swift", "Testing", "AWS"],
        "salary_pkr":  "90K – 185K/month",
        "salary_usd":  "$30K – $72K/year",
        "demand":      "Very High",
        "description": "Build beautiful cross-platform mobile and web apps using Flutter.",
    },
    {
        "title":       "Android Developer",
        "category":    "Mobile",
        "emoji":       "🤖",
        "core_skills": ["Android", "Java", "SQL"],
        "good_skills": ["REST APIs", "Git", "Firebase", "Agile/Scrum"],
        "bonus_skills":["Kotlin", "Testing", "AWS"],
        "salary_pkr":  "85K – 175K/month",
        "salary_usd":  "$28K – $68K/year",
        "demand":      "High",
        "description": "Build native Android applications using Java or Kotlin.",
    },
    {
        "title":       "iOS Developer",
        "category":    "Mobile",
        "emoji":       "🍎",
        "core_skills": ["iOS/Swift", "REST APIs", "Git"],
        "good_skills": ["SQL", "Firebase", "Testing", "Agile/Scrum"],
        "bonus_skills":["React Native", "AWS", "CI/CD"],
        "salary_pkr":  "100K – 200K/month",
        "salary_usd":  "$35K – $80K/year",
        "demand":      "Medium",
        "description": "Build native iOS applications using Swift and Apple frameworks.",
    },
    {
        "title":       "Mobile App Developer",
        "category":    "Mobile",
        "emoji":       "📲",
        "core_skills": ["React Native", "Flutter", "REST APIs"],
        "good_skills": ["JavaScript", "Firebase", "Git", "SQL"],
        "bonus_skills":["Android", "iOS/Swift", "Testing"],
        "salary_pkr":  "85K – 180K/month",
        "salary_usd":  "$28K – $70K/year",
        "demand":      "Very High",
        "description": "Build cross-platform mobile experiences for both iOS and Android.",
    },

    # ── AI / ML / DATA ──────────────────────────────────────────────────────
    {
        "title":       "Machine Learning Engineer",
        "category":    "AI/ML",
        "emoji":       "🤖",
        "core_skills": ["Machine Learning", "Python", "Data Analysis"],
        "good_skills": ["Deep Learning", "SQL", "Git", "Docker"],
        "bonus_skills":["AWS", "TensorFlow", "PyTorch", "NLP"],
        "salary_pkr":  "120K – 250K/month",
        "salary_usd":  "$45K – $110K/year",
        "demand":      "Very High",
        "description": "Build and deploy machine learning models that solve real business problems.",
    },
    {
        "title":       "AI Engineer",
        "category":    "AI/ML",
        "emoji":       "🧠",
        "core_skills": ["Python", "Machine Learning", "Deep Learning"],
        "good_skills": ["LLM/GenAI", "NLP", "Docker", "FastAPI", "Git"],
        "bonus_skills":["AWS", "Computer Vision", "PyTorch", "TensorFlow"],
        "salary_pkr":  "130K – 280K/month",
        "salary_usd":  "$50K – $130K/year",
        "demand":      "Extremely High",
        "description": "Design and implement AI systems, LLM applications, and intelligent pipelines.",
    },
    {
        "title":       "Data Scientist",
        "category":    "AI/ML",
        "emoji":       "📊",
        "core_skills": ["Python", "Data Analysis", "Machine Learning"],
        "good_skills": ["SQL", "Deep Learning", "Git", "SQL Analytics"],
        "bonus_skills":["AWS", "NLP", "Docker", "Agile/Scrum"],
        "salary_pkr":  "110K – 230K/month",
        "salary_usd":  "$40K – $100K/year",
        "demand":      "Very High",
        "description": "Extract insights from data using statistical analysis and ML models.",
    },
    {
        "title":       "Data Analyst",
        "category":    "AI/ML",
        "emoji":       "📈",
        "core_skills": ["Data Analysis", "SQL", "Python"],
        "good_skills": ["SQL Analytics", "Git", "Agile/Scrum"],
        "bonus_skills":["Machine Learning", "AWS", "Figma/UI"],
        "salary_pkr":  "80K – 160K/month",
        "salary_usd":  "$25K – $65K/year",
        "demand":      "High",
        "description": "Analyse business data to inform decisions using SQL and Python.",
    },
    {
        "title":       "NLP Engineer",
        "category":    "AI/ML",
        "emoji":       "💬",
        "core_skills": ["NLP", "Python", "Machine Learning"],
        "good_skills": ["Deep Learning", "LLM/GenAI", "Git", "Docker"],
        "bonus_skills":["AWS", "FastAPI", "TensorFlow", "PyTorch"],
        "salary_pkr":  "120K – 260K/month",
        "salary_usd":  "$45K – $115K/year",
        "demand":      "Very High",
        "description": "Build systems that understand, process, and generate human language.",
    },
    {
        "title":       "Computer Vision Engineer",
        "category":    "AI/ML",
        "emoji":       "👁️",
        "core_skills": ["Computer Vision", "Python", "Deep Learning"],
        "good_skills": ["TensorFlow", "PyTorch", "Git", "Docker"],
        "bonus_skills":["AWS", "FastAPI", "Machine Learning", "Linux"],
        "salary_pkr":  "120K – 260K/month",
        "salary_usd":  "$45K – $115K/year",
        "demand":      "High",
        "description": "Build systems that interpret and analyse visual data from the world.",
    },
    {
        "title":       "GenAI / LLM Engineer",
        "category":    "AI/ML",
        "emoji":       "✨",
        "core_skills": ["LLM/GenAI", "Python", "NLP"],
        "good_skills": ["FastAPI", "Docker", "Git", "Machine Learning"],
        "bonus_skills":["AWS", "Deep Learning", "REST APIs", "Testing"],
        "salary_pkr":  "150K – 350K/month",
        "salary_usd":  "$60K – $160K/year",
        "demand":      "Extremely High",
        "description": "Build applications powered by large language models and generative AI.",
    },

    # ── DEVOPS / CLOUD ──────────────────────────────────────────────────────
    {
        "title":       "DevOps Engineer",
        "category":    "DevOps",
        "emoji":       "🔧",
        "core_skills": ["Docker", "CI/CD", "Linux"],
        "good_skills": ["AWS", "Kubernetes", "Git", "Python", "Terraform"],
        "bonus_skills":["Microservices", "Testing", "Agile/Scrum"],
        "salary_pkr":  "120K – 250K/month",
        "salary_usd":  "$45K – $110K/year",
        "demand":      "Very High",
        "description": "Build and maintain the infrastructure and pipelines that ship software.",
    },
    {
        "title":       "Cloud Engineer",
        "category":    "DevOps",
        "emoji":       "☁️",
        "core_skills": ["AWS", "Docker", "Linux"],
        "good_skills": ["Kubernetes", "Terraform", "CI/CD", "Python", "Git"],
        "bonus_skills":["Azure", "GCP", "Microservices", "Testing"],
        "salary_pkr":  "130K – 270K/month",
        "salary_usd":  "$50K – $120K/year",
        "demand":      "Very High",
        "description": "Design and manage cloud infrastructure on AWS, Azure, or GCP.",
    },
    {
        "title":       "Site Reliability Engineer",
        "category":    "DevOps",
        "emoji":       "🛡️",
        "core_skills": ["Linux", "Docker", "Python"],
        "good_skills": ["Kubernetes", "AWS", "CI/CD", "Git", "Terraform"],
        "bonus_skills":["Microservices", "Testing", "Agile/Scrum"],
        "salary_pkr":  "140K – 280K/month",
        "salary_usd":  "$55K – $125K/year",
        "demand":      "High",
        "description": "Ensure reliability, scalability, and performance of production systems.",
    },

    # ── DATABASE ────────────────────────────────────────────────────────────
    {
        "title":       "Database Administrator",
        "category":    "Database",
        "emoji":       "🗄️",
        "core_skills": ["SQL", "MongoDB", "Linux"],
        "good_skills": ["Python", "Docker", "Git", "AWS"],
        "bonus_skills":["Redis", "Elasticsearch", "Agile/Scrum"],
        "salary_pkr":  "90K – 180K/month",
        "salary_usd":  "$30K – $70K/year",
        "demand":      "Medium",
        "description": "Design, manage, and optimise databases for performance and reliability.",
    },

    # ── SOFTWARE ENGINEERING ────────────────────────────────────────────────
    {
        "title":       "Software Engineer",
        "category":    "Software Engineering",
        "emoji":       "💻",
        "core_skills": ["Python", "Git", "REST APIs"],
        "good_skills": ["SQL", "Docker", "Agile/Scrum", "Testing"],
        "bonus_skills":["AWS", "Microservices", "TypeScript", "Linux"],
        "salary_pkr":  "100K – 220K/month",
        "salary_usd":  "$35K – $90K/year",
        "demand":      "Very High",
        "description": "Design, develop, and maintain software systems across the full stack.",
    },
    {
        "title":       "QA Engineer",
        "category":    "Software Engineering",
        "emoji":       "🧪",
        "core_skills": ["Testing", "Python", "Git"],
        "good_skills": ["Agile/Scrum", "SQL", "REST APIs", "Docker"],
        "bonus_skills":["CI/CD", "JavaScript", "Linux"],
        "salary_pkr":  "70K – 140K/month",
        "salary_usd":  "$22K – $55K/year",
        "demand":      "High",
        "description": "Ensure software quality through manual and automated testing strategies.",
    },
    {
        "title":       "API Developer",
        "category":    "Backend",
        "emoji":       "🔌",
        "core_skills": ["REST APIs", "Python", "SQL"],
        "good_skills": ["FastAPI", "Docker", "Git", "Testing"],
        "bonus_skills":["GraphQL", "AWS", "MongoDB", "Microservices"],
        "salary_pkr":  "85K – 170K/month",
        "salary_usd":  "$28K – $65K/year",
        "demand":      "High",
        "description": "Design and build RESTful and GraphQL APIs consumed by clients and partners.",
    },
    {
        "title":       "Microservices Architect",
        "category":    "Software Engineering",
        "emoji":       "🏗️",
        "core_skills": ["Microservices", "Docker", "REST APIs"],
        "good_skills": ["Kubernetes", "Python", "AWS", "Git"],
        "bonus_skills":["GraphQL", "Testing", "CI/CD", "Linux"],
        "salary_pkr":  "150K – 320K/month",
        "salary_usd":  "$60K – $140K/year",
        "demand":      "High",
        "description": "Design distributed systems using microservices architecture patterns.",
    },
]
